/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    HeaderApp: typeof import('./src/components/HeaderApp.vue')['default']
    MainContainer: typeof import('./src/components/MainContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Vulnerabilities: typeof import('./src/components/Vulnerabilities.vue')['default']
  }
}
